config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root "pages#landing"

  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "join/:invite_code", to: "clubs#join_by_code", as: :join_by_code
  resources :sessions, only: [ :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  namespace :authentications do
    resources :events, only: :index
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "users/:user_id/masquerade", to: "masquerades#create", as: :user_masquerade
  post "accept_invitation/:club_id", to: "members#accept", as: :accept_invitation
  delete "deny_invitation/:club_id", to: "members#deny", as: :deny_invitation
  get "unsubscribe/:token", to: "members#unsubscribe", as: :unsubscribe_club
  delete "unsubscribe/:token", to: "members#process_unsubscribe", as: :process_unsubscribe

  resources :clubs do
    get "random_question", on: :member
    resources :members do
      member do
        patch :change_role
        post :resend_invitation
      end
    end
    resources :issues do
      resources :issue_questions
      resources :answers do
        resources :comments, only: [ :create ]
      end
      post "deliver", to: "issues#deliver", as: :deliver
      post "reply", to: "answers#create", as: :reply
      get "reply", to: "answers#new", as: :new_reply
      get "reply/edit", to: "answers#edit", as: :edit_reply
    end
    resources :questions
  end

  get "impersonate/:user_id", to: "impersonations#create", as: :impersonate

  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :updates, only: [ :index, :show ]
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :club
  has_many :issue_questions, dependent: :destroy
  has_many :answers, through: :issue_questions

  accepts_nested_attributes_for :issue_questions, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true
  validate :no_updates_after_sent, on: :update

  before_validation :set_defaults
  before_save :clean_inputs
  before_destroy :remove_all_jobs_for_issue
  after_create :generate_questions, :generate_sections
  after_create :schedule_reminders, :schedule_delivery
  after_update :reschedule_reminders, :reschedule_delivery, if: :saved_change_to_deliver_at?

  scope :in_progress, -> { where("open_at < ? AND deliver_at > ? AND sent_at IS NULL", Time.current, Time.current) }
  scope :upcoming, -> { where("deliver_at > ?", Time.current) }
  scope :sent, -> { where("sent_at IS NOT NULL").order(sent_at: :desc) }
  scope :unsent, -> { where(sent_at: nil) }
  scope :deliverable, -> { where("deliver_at <= ? AND sent_at IS NULL", Time.current) }
  scope :chronological, -> { order(:deliver_at) }

  def questions
    issue_questions.where(section: "questions")
  end

  def questions_grouped_by_section
    sort_order = Club.sections
    issue_questions.group_by(&:section).sort_by { |section, _| sort_order.index(section.to_sym) }
  end

  # Used to get a members answers or all answers for the issue, grouped by section
  # @param member [Member, nil] The member to get answers for, or nil for all answers
  # @return [[{:key=>"", <ClubSection>, :questions=>[{question: <IssueQuestion>, answers: [<Answer>]}]}] An array of hashes containing the section, questions, and answers for the issue
  def sections_questions_answers(member = nil, visible_members = nil)
    # For non-admins, exclude admin only sections when viewing own answers
    exclude = member && !member&.can_manage? ? Club.admin_only_sections.map(&:to_s) : []
    sections = self.sections - exclude
    answer = proc { |q|
      if member
        [ q.answers.find_or_initialize_by(member: member) ]
      else
        visible_members ? q.answers.where(member: visible_members) : q.answers
      end
    }
    sections.map do |section|
      {
        key: section,
        questions: issue_questions.in_section(section).map do |q|
          { question: q, answers: answer.call(q) }
        end
      }
    end.reject { |section| section[:questions].empty? }
  end

  def issue_answers
    answers.includes(:issue_question).group_by { |a| a.issue_question.section }
  end

  def generate_sections
    # Exclude the questions section because it is handled separately
    excluded_sections = [ :questions ]
    Club.sections.each do |key|
      next if excluded_sections.include?(key)
      option = Club.sections_options[key]
      issue_questions.create!(title: option[:title], prompt: option[:description], section: key.to_s, asked_by: "System", kind: option[:kind], options: option[:options])
    end
  end

  def generate_questions(count = club.default_number_questions)
    return unless sections.include?("questions")

    questions = Question.order("RANDOM()").limit(count)
    issue_questions.create!(questions.map { |q| q.attributes.slice("prompt", "category", "asked_by") })
  end

  def in_progress?
    open_at < Time.current && deliver_at > Time.current && sent_at.nil?
  end

  def upcoming?
    open_at > Time.current && sent_at.nil?
  end

  def sent?
    sent_at.present?
  end

  def unsent?
    sent_at.nil?
  end

  def waiting_for_reply?(member)
    in_progress? && !answered_by?(member)
  end

  def answered_by?(member)
    answers.where(member: member).any?
  end

  def section_enabled?(section)
    sections.include?(section.to_s)
  end

  def enabled_answers
    answers.where(issue_questions: { section: sections })
  end

  def enabled_answers_for_member(member)
    enabled_answers.where(member: member)
  end

  def time_until_delivery
    deliver_at - Time.current
  end

  def deliver(send_emails = true, notify_club = true)
    return if sent?
    remove_all_jobs_for_issue

    send_delivery_emails if send_emails
    update(sent_at: Time.current)
    club.notify_club_of_delivery(self) if notify_club
  end

  def send_delivery_emails
    club.members.active.each do |member|
      IssueMailer.deliver_issue(member, self).deliver_later
    end
  end

  def send_reminder_emails
    return unless in_progress?

    club.members.active.each do |member|
      unless answered_by?(member)
        IssueMailer.reply_reminder(member, self).deliver_later
      end
    end
  end

  def undeliver
    update(sent_at: nil)
  end

  def reschedule_reminders_and_delivery
    reschedule_reminders
    reschedule_delivery
  end

  private

  def set_defaults
    return if club.nil?
    self.sections ||= club.active_sections
    self.title ||= "Issue ##{club.issues.count + 1}"
    self.deliver_at ||= Time.current.in_time_zone(club.timezone).beginning_of_day + club.frequency_in_days.days + club.delivery_time_in_hours.hours
    self.open_at ||= self.deliver_at - 7.days
  end

  def clean_inputs
    self.sections = sections.reject(&:blank?)
    self.deliver_at = deliver_at.change(sec: 0)
    self.open_at = open_at.change(sec: 0)
  end

  def schedule_reminders
    intervals = [ 1.month, 1.week, 3.days, 1.day ]
    intervals.each do |interval|
      # This condition checks if it's appropriate to schedule a reminder:
      # 1. The reminder time (deliver_at - interval) should not be before the issue opens (>= open_at)
      # 2. The reminder time should be in the future (> Time.current)
      # 3. The reminder should be at least 1 day after the issue opens
      # If both conditions are met, we schedule a reminder for this interval
      if deliver_at - interval >= open_at && deliver_at - interval > Time.current && deliver_at - interval >= open_at + 1.day
        schedule_reminder(interval)
      end
    end
  end

  def schedule_delivery
    IssueDeliveryJob.set(wait_until: deliver_at.in_time_zone(club.timezone)).perform_later(id)
  end

  def schedule_reminder(interval)
    reminder_time = deliver_at.in_time_zone(club.timezone) - interval
    IssueReminderJob.set(wait_until: reminder_time).perform_later(id, interval)
  end

  def reschedule_reminders
    jobs_for_issue("IssueReminderJob").each(&:destroy)
    schedule_reminders
  end

  def reschedule_delivery
    jobs_for_issue("IssueDeliveryJob").each(&:destroy)
    schedule_delivery
  end

  def remove_all_jobs_for_issue
    jobs_for_issue.each(&:destroy!)
  end

  # TODO: do better
  def jobs_for_issue(class_name = nil, id = self.id)
    jobs = class_name ? SolidQueue::Job.where(class_name: class_name) : SolidQueue::Job.all
    jobs.select { |job| job.arguments["arguments"].include?(id) }
  end

  def no_updates_after_sent
    if sent_at_was.present? && (changes.keys - [ "sent_at" ]).any?
      errors.add(:base, "Cannot update issue after it has been sent, except to undeliver")
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  layout :resolve_layout
  before_action :set_issue, only: %i[ show edit update destroy deliver ]

  # GET /issues or /issues.json
  def index
    @club = Club.find(params[:club_id])
    authorize! @club, to: :show?
    @in_progress = @club.issues.in_progress
    @upcoming = @club.issues.upcoming
    @sent = @club.issues.sent
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
    redirect_to club_issue_path(@issue.club, @issue), notice: "Cannot edit an issue that has already been sent" if @issue.sent?
    @club = Club.find(params[:club_id])
    @issue = @club.issues.find(params[:id])
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issue_url(@issue), notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.turbo_stream do
          flash.now[:notice] = "Issue was successfully updated."
          render turbo_stream: turbo_stream.replace(
            "issue_form",
            partial: "form",
            locals: { issue: @issue }
          )
        end
        format.html { redirect_to edit_club_issue_path(@issue.club, @issue), notice: "Issue was successfully updated." }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "issue_form",
            partial: "form",
            locals: { issue: @issue }
          )
        end
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy!

    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def deliver
    if @issue.sent?
      @issue.send_delivery_emails
      redirect_to club_issue_path(@issue.club, @issue), notice: "Issue delivery emails resent."
    else
      @issue.deliver
      redirect_to club_issue_path(@issue.club, @issue), notice: "Issue delivery emails sent."
    end
  end

  private

  def resolve_layout
    case action_name
    when "edit", "show", "new"
      "issue"
    else
      "club"
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find(params[:id] || params[:issue_id])
    authorize! @issue
    @club = @issue.club
  end

  def issue_params
    params.require(:issue).permit(:title, :deliver_at, :open_at, sections: [], issue_questions_attributes: [ :id, :prompt, :asked_by, :category, :priority, :_destroy ])
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def all_images(answers)
    answers.flat_map do |answer|
      if answer.images.attached?
        answer.images.map do |image|
          { image: image, author: answer.member.display_name, content: answer.content }
        end
      else
        []
      end
    end
  end
end

app/views/issues/_form.html.erb
<%= turbo_frame_tag "issue_form" do %>
  <%= form_with(model: issue, url: club_issue_path(issue.club, issue), method: :patch, local: true, data: { turbo: false }) do |form| %>
    <div>
      <h3>Issue Sections</h3>
      <p class="subtitle">Select the sections you want to include in this issue. (Does not affect other issues)</p>

      <%= form.collection_check_boxes :sections, section_options, :first, :last do |b| %>
        <p class="flex items-center">
          <%= b.check_box(class: "mr-2 h-5 w-5", checked: issue.section_enabled?(b.value)) %>
          <%= b.label(class: "text-lg") do %>
            <%= b.object.last[:title] %>
            <i class="text-sm text-[var(--secondary-color)]"><%= b.object.last[:description] %></i>
          <% end %>
        </p>
      <% end %>
    </div>

    <div class="mt-6">
      <h3>Issue Opening</h3>
      <p class="subtitle">Set the Opening Date for this issue.</p>
      <%= form.datetime_local_field :open_at, class: "" %>
      <p class="text-sm text-gray-500 mt-1">Timezone: <%= Time.zone.name %></p>
    </div>

    <div class="mt-6">
      <h3>Issue Delivery</h3>
      <p class="subtitle">Set the delivery for this issue.</p>
      <%= form.datetime_local_field :deliver_at, class: "" %>
      <p class="text-sm text-gray-500 mt-1">Timezone: <%= Time.zone.name %></p>
    </div>

    <div class="mt-6">
      <%= component 'submit_button', form: form, text: "Update", cancel_path: club_issues_path(issue.club) %>
    </div>
  <% end %>
<% end %>

app/views/issues/_issue.html.erb
<div id="<%= dom_id issue %>" class="frame p-4 pt-2 flex flex-col justify-between gap-4">
  <div>
    <div class="flex justify-between items-end">
      <span class="text-sm <%= 
        case
        when issue.in_progress?
          'text-[var(--success-color)]'
        when issue.upcoming?
          'text-[var(--warning-color)]'
        when issue.sent?
          'text-[var(--info-color)]'
        else
          'text-gray-500'
        end %>">
        <%= case
          when issue.in_progress? then 'In Progress'
          when issue.upcoming? then 'Upcoming'
          when issue.sent? then 'Sent'
          else 'Unknown'
        end %>
      </span>


       <div data-controller="dropdown" class="relative">
        <button data-action="click->dropdown#toggle" class="text-lg font-bold">…</button>
        <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10">
          <%= link_to "Edit Reply",club_issue_new_reply_path(issue.club, issue), class: "block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
          <%= link_to "Edit Issue", edit_club_issue_path(issue.club, issue), class: "block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" unless issue.sent? || !allowed_to?(:update?, issue) %>
          <%= render 'shared/modal',
                 modal_id: 'delete-issue-modal',
                 button_classes: 'block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100',
                 button_text: 'Delete Issue',
                 title: 'Delete Issue',
                 required_input: 'DELETE',
                 required_input_message: 'Type DELETE to confirm',
                 confirm_button: link_to("Delete Issue", club_issue_path(issue.club, issue), method: :delete, class: 'button outline danger', data: { turbo_method: :delete }) do %>
        <p>Are you sure you want to delete this issue?</p>
          <p class="text-[var(--danger-color)]">This action cannot be undone.</p>
        <% end if allowed_to?(:destroy?, issue)%>
       <%= render 'shared/modal',
                 modal_id: 'deliver-issue-modal',
                 button_classes: 'block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100',
                 button_text: 'Deliver Issue',
                 title: 'Deliver Issue',
                 confirm_button: link_to("Confirm Delivery", club_issue_deliver_path(issue.club, issue), method: :post, class: 'button secondary warning', data: { turbo_method: :post }) do %>
        <p>Are you sure you want to deliver this issue now?</p>
        <p>This will send the issue to all club members immediately.</p>
      <% end if allowed_to?(:update?, issue) && !issue.sent? %>
             <%= render 'shared/modal',
                 modal_id: 'deliver-issue-modal',
                 button_classes: 'block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100',
                 button_text: 'Re-deliver Issue',
                 title: 'Re-deliver Issue',
                 confirm_button: link_to("Confirm Re-delivery", club_issue_deliver_path(issue.club, issue), method: :post, class: 'button secondary warning', data: { turbo_method: :post }) do %>
        <p>Are you sure you want to re-deliver this issue now?</p>
        <p>This will re-send the issue to all club members immediately.</p>
      <% end if allowed_to?(:update?, issue) && issue.sent? %>
      <%= render 'shared/modal',
                 modal_id: 'see-issue-modal',
                 button_classes: 'block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100',
                 button_text: 'Preview Issue',
                 title: 'Preview Issue',
                 confirm_button: link_to('Preview Issue', club_issue_path(issue.club, issue), class: 'button secondary warning' ) do %>
        <p>Are you sure you want to see this issue now?</p>
        <p>It's more fun to wait until the delivery after everyone's responded.</p>
      <% end unless issue.sent? %>
      <%= link_to "View Issue", club_issue_path(issue.club, issue), class: "block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" if issue.sent? %>
    </div>
</div>

    </div>
    <div class="">
      <hgroup>
        <h2 class=""><%= issue.title %></h2>
        <p class="text-xs mt-2">
          <% if issue.sent? %>
            Sent on:<br> <%= I18n.l(issue.sent_at, format: "%a %b %d, %Y at %I:%M %p %Z") %>
          <% elsif issue.in_progress? %>
            Delivers on:<br> <%= I18n.l(issue.deliver_at, format: "%a %b %d, %Y at %I:%M %p %Z") %>
          <% elsif issue.upcoming? %>
            Open for replies on:<br> <%= I18n.l(issue.open_at, format: "%a %b %d, %Y at %I:%M %p %Z") %>
          <% end %>
        </p>
      </hgroup>
    </div>
    </div>
    <%= link_to "Reply Now", club_issue_new_reply_path(issue.club, issue), class: "justify-end button text-center #{issue.in_progress? ? '' : 'secondary'}" if issue.waiting_for_reply?(issue.club.membership(current_user))%>
    <%= link_to "Update Reply", club_issue_edit_reply_path(issue.club, issue), class: "justify-end button text-center" if issue.answered_by?(issue.club.membership(current_user)) && !issue.sent? %>
    <%= link_to "View", club_issue_path(issue.club, issue), class: "justify-end button text-center" if issue.sent? %>
</div>

app/views/issues/edit.html.erb
<div class="w-full">
  <h3 class="mt-2">Questions</h3>
  <p class="subtitle">These questions will appear in <%= @issue.title %> under the Questions section.</p>

  <div id="issue-questions" class="space-y-4">
    <%= render @issue.questions %>
  </div>
  <div class="">
    <%= render 'shared/modal',
               modal_id: 'new-question-modal',
               button_classes: 'button secondary mt-4',
               button_text: '+ Add Question',
               title: 'Add New Question',
               content: render('issue_questions/form', issue_question: @issue.issue_questions.build) %>
  </div>

  <div class="my-12">
    <%= render 'form', issue: @issue %>
  </div>

app/views/issues/index.html.erb
<% if @in_progress.empty? && @upcoming.empty?%>
<div class="frame my-4 py-8">
  <p class="text-center text-gray-500">No current issues</p>
  <% if current_user.can_manage?(@club) && @club.inactive? %>
    <p class="text-center text-gray-500 my-2">Your club is inactive. Go to
      <%= link_to 'Club Settings', edit_club_path(@club), class: "underline font-bold"%> to activate it.
    </p>
    <% end %>
  </div>
<% end %>

<div class="grid gap-4 md:grid-cols-2">
  <div class="col-span-2">
  <%= render @in_progress %>
  </div>
  <h3 class="text-lg font-bold border-t col-span-2 text-left pt-4">Next Up</h3>
  <%= render @upcoming %>
  <h3 class="text-lg font-bold border-t col-span-2 text-left pt-4">Past Issues</h3>
  <%= render @sent %>
</div>

app/views/issues/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New issue</h1>

  <%= render "form", issue: @issue %>

  <%= link_to "Back to issues", issues_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/issues/show.html.erb
<div class="theme--<%= @issue.club.theme || 'base' %> md:max-w-2xl md:mx-auto pt-15 overflow-auto">
  <div class="w-full md:max-w-[650px] md:mx-auto mb-8 overflow-visible">
    <h1 class="my-1"><%= @issue.club.title %></h1>
    <h3 class=""><%= @issue.title %> | <%= @issue.deliver_at.strftime("%B %d, %Y") %></h4>
    <hr class="my-1">
    <p class="text-sm m-0 secondary-color">Made by <%= @issue.club.members.active.pluck(:display_name).to_sentence %></p>

    <% @issue.sections_questions_answers(nil, @issue.club.visible_members(@member || @issue.club.membership(current_user))).each do |section| %>
      <div class="mt-10">
        <% if section[:key] != "questions" %>
          <h3 class="font-semibold"><%= t("clubs.sections.#{section[:key]}.title") %></h3>
        <% end %>

        <% section[:questions].each do |qa| %>
          <div class="">
            <% if qa[:question].section == "questions" %>
              <h3 class="font-semibold"><%= qa[:question].prompt %></h3>
            <% end %>
            <div class="flex flex-col space-y-4 mt-4">
              <%= render qa[:answers].reject(&:unanswered?) %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @issue.club.upcoming_issue.present? %>
      <div class="mt-10 text-center">
        The next issue of <a href="<%= club_url(@issue.club) %>" class="italic underline underline-offset-2"><%= @issue.club.title %></a> will be delivered
        on <strong><%= @issue.club.upcoming_issue.deliver_at.strftime("%B %d, %Y") %></strong>
      </div>
    <% end %>
    <div class="mt-10 text-center">
      <%= link_to root_url do %>
        <%= image_tag 'mailpals_logo_rect.png', alt: 'MailPals Logo', class: 'w-24 mx-auto' %>
      <% end %>
    </div>
  </div>
</div>