config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  root "pages#landing"

  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "join/:invite_code", to: "clubs#join_by_code", as: :join_by_code
  resources :sessions, only: [ :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  namespace :authentications do
    resources :events, only: :index
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "users/:user_id/masquerade", to: "masquerades#create", as: :user_masquerade
  post "accept_invitation/:club_id", to: "members#accept", as: :accept_invitation
  delete "deny_invitation/:club_id", to: "members#deny", as: :deny_invitation
  get "unsubscribe/:token", to: "members#unsubscribe", as: :unsubscribe_club
  delete "unsubscribe/:token", to: "members#process_unsubscribe", as: :process_unsubscribe

  resources :clubs do
    get "random_question", on: :member
    resources :members do
      member do
        patch :change_role
        post :resend_invitation
      end
    end
    resources :issues do
      resources :issue_questions
      resources :answers do
        resources :comments, only: [ :create ]
      end
      post "deliver", to: "issues#deliver", as: :deliver
      post "reply", to: "answers#create", as: :reply
      get "reply", to: "answers#new", as: :new_reply
      get "reply/edit", to: "answers#edit", as: :edit_reply
    end
    resources :questions
  end

  get "impersonate/:user_id", to: "impersonations#create", as: :impersonate

  # resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :updates, only: [ :index, :show ]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :member
  belongs_to :issue_question

  has_many :comments, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :member_id, presence: true
  validates :issue_question_id, presence: true
  validates :member_id, uniqueness: { scope: :issue_question_id }
  validate :no_updates_after_delivery, on: :update

  scope :by_question, ->(question) { where(issue_question: question) }
  scope :by_member, ->(member) { where(member: member) }

  def unanswered?
    content.blank? && images.empty?
  end

  def self.member_answers(member)
    where(member: member)
  end

  def club
    issue_question.club
  end

  def issue
    issue_question.issue
  end

  private

  def no_updates_after_delivery
    if issue_question.issue.sent?
      errors.add(:base, "Cannot update answer after issue has been delivered")
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  layout "issue"
  before_action :set_current

  def index
    redirect_to club_issues_url(@club)
  end

  def show; end

  def new
    @sqa = @issue.sections_questions_answers(@member)
  end

  def edit
    flash.now[:alert] = "This issue email has already been sent. Any updates will only be reflected on the Mailpals website." if @issue.sent?
    @sqa = @issue.sections_questions_answers(@member)
  end

  def create
    begin
      Answer.transaction do
        @answers = answer_params.to_h.map do |id, answer_data|
          answer = Answer.find_or_initialize_by(
            issue_question_id: id,
            member: @member,
          )
          answer.update!(
            answer_data.except(:images)
          )
          answer.images.attach(answer_data[:images]) if answer_data[:images].present?
        end
        if params[:photo_ids_to_delete].present?
          params[:photo_ids_to_delete].each do |id|
            ActiveStorage::Blob.find(id).attachments.each(&:purge)
          end
        end
      end
      redirect_to club_issues_url(@club), notice: "Answers were successfully created.", flash: { confetti: true }
    rescue ActiveRecord::RecordInvalid => exception
      flash.now[:alert] = exception.record.errors.full_messages.join("<br/>")
      @sqa = @issue.sections_questions_answers(@member)
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @issue.answers.where(member: @member).destroy_all
    redirect_to answers_url, notice: "Answer was successfully destroyed."
  end

  private

  def set_current
    @club = Club.find(params[:club_id])
    authorize! @club, to: :show?
    @member = @club.membership(current_user)
    @issue = @club.issues.find(params[:issue_id])
    @answer = @issue.answers.find(params[:id]) if params[:id].present?
  end

  def answer_params
    params.permit(answers: [ :issue_question_id, :content, images: [], photo_ids_to_delete: [] ]).require(:answers)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<% comments_hidden = params[:answer] == answer.id.to_s ? '' : 'hidden' %>

<div id="answer-<%= answer.id %>" class="my-2">
  <% if answer.images.attached? %>
    <% answer.images.each do |image| %>
      <div class="mt-5 border-[var(--primary-color)] overflow-hidden">
        <%= image_tag url_for(image), alt: "Image from #{answer.member.display_name}", class: "max-w-full h-auto align-middle inline-block" %>
        <p class="px-7 py-2 m-0 text-sm bg-amber-50 rounded rounded-t-none"><strong><%= answer.member.display_name %></strong><%= "<span class='font-normal'> #{answer.content}</span>" if answer.content.present? %></p>
      </div>
    <% end %>
  <% else %>
    <div class="px-7 py-4 m-0 text-sm bg-amber-50 rounded"><strong><%= answer.member.display_name %></strong><%= format_and_sanitize_text(answer.content) if answer.content.present? %></div>
  <% end %>

 <% if action_name.eql?('show') %>
  <div class="mt-2" data-controller="toggle-class">
    <div class="flex items-center justify-between">
      <button class="text-sm text-gray-300 hover:text-gray-700 flex items-center" data-action="click->toggle-class#toggle">
        Comments (<span id="comment-count-<%= answer.id %>"><%= answer.comments.count %></span>)
      </button>
      <%= render 'shared/modal',
        modal_id: "new-comment-modal-#{answer.id}",
        button_classes: 'text-sm text-gray-300 hover:text-gray-700',
        button_text: -> do
          tag.span class: 'flex items-center' do
            concat "Add Comment"
          end
        end,
        title: 'Add New Comment',
        subtitle: "Add a comment to #{answer.member.display_name}'s response to '#{answer.issue_question.prompt}'",
        content: render('comments/form', comment: Comment.new, answer: answer, question: answer.issue_question.prompt, response: answer.content),
        open_on_connect: params[:comment_on] == answer.id.to_s %>
    </div>
    <div id="comments-<%= answer.id %>" class="<%= comments_hidden %> ml-2 pl-4 border-l mt-2 space-y-2" data-toggle-class-target="toggleable">
      <%= render answer.comments.order(created_at: :asc) %>
    </div>
  </div>
  <% else %>
    <div class="mt-2 font-light text-xs text-right">
      <%= link_to club_issue_url(@issue.club, @issue, anchor: "answer-#{answer.id}", params: { answer: answer.id, comment_on: answer.id }), class: "text-sm text-gray-300 hover:text-gray-700" do %>
      Add Comment
    <% end %>
  </div>
<% end %>
</div>

app/views/answers/_form.html.erb
<%= form_with(url: club_issue_answers_path(@club, @issue), class: "") do |form| %>
  <% error_count = @answers&.select { |answer| answer.errors.any? }&.sum { |answer| answer.errors.count } %>
  <% if error_count&.positive? %>
    <div id="error_explanation" class="text-red-500">
      <h2><%= pluralize(error_count, "error") %> prohibited these answers from being saved:</h2>
      <ul>
        <% @answers.each do |answer| %>
          <% answer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @sqa.each_with_index do |sqa, _index| %>
    <div class="mt-6">
      <h3><%= t("#{sqa[:key]}.title", scope: [:clubs, :sections]) %></h3>
      <p class="subtitle"><i><%= t("#{sqa[:key]}.description", scope: [:clubs, :sections]) %></i></p>
    </div>

    <% sqa[:questions].each do |question| %>
      <% answer = question[:answers][0] %>
      <% form.object = answer %>
      <div class="mt-4">
        <% if question[:question].section == "questions" %>
          <p class="border-l-2 border-gray-300 pl-2 mb-2"><%= answer.issue_question.prompt %></p>
        <% end %>
        <% if answer.issue_question.kind == "select" || answer.issue_question.kind == "radio" %>
          <% answer.issue_question.options.each do |option| %>
            <p class="flex items-center">
              <%= form.radio_button "answers[#{answer.issue_question_id}][content]", option, class: "mr-2 h-5 w-5" %>
              <%= form.label "answers[#{answer.issue_question_id}][content][#{option}]", option, class: "text-lg" %>
            </p>
          <% end %>
        <% elsif answer.issue_question.kind == "checkbox" %>
          <% answer.issue_question.options.each do |option| %>
            <p class="flex items-center">
              <%= form.check_box "answers[#{answer.issue_question_id}][content][#{option}]", class: "mr-2 h-5 w-5" %>
              <%= form.label "answers[#{answer.issue_question_id}][content][#{option}]", option, class: "text-lg" %>
            </p>
          <% end %>
        <% elsif answer.issue_question.kind == "image" %>
          <%= render 'shared/photo_upload', form: form, form_field: "answers[#{answer.issue_question_id}][images]" %>
        <% else %>
          <%= form.text_area "answers[#{answer.issue_question_id}][content]", rows: 4, placeholder: "Write something here...", value: answer.content, class: "w-full" %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="mt-6">
    <div class="tw-grid grid-cols-3 gap-2">
      <%= component 'submit_button', form: form, cancel_path: club_issues_path(@club) %>
    </div>
    <p class="text-sm text-gray-500 mt-1">You can always edit your reply before delivery!</p>
  </div>
<% end %>

app/views/answers/edit.html.erb
<div class="mb-6">
  <%= render "form", answers: @answers %>
</div>

app/views/answers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Answers" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Answers</h1>
    <%= link_to "New answer", new_answer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="answers" class="min-w-full">
    <% @answers.each do |answer| %>
      <%= render answer %>
      <p>
        <%= link_to "Show this answer", answer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<div class="mb-6">
  <h1 class="text-lg">Replying as <%= @member.display_name %></h1>
  <%= render "form", answers: @answers %>
</div>

app/views/answers/show.html.erb
<div class="mb-4">
  <h2 class="text-xl font-semibold mb-2">Question:</h2>
  <p class="text-gray-700"><%= @answer.issue_question.prompt %></p>
</div>

<%= render @answer %>